### ISSUE TITLE
Is it possible to preserver line breaks?

### ISSUE THREAD

**Issue by ilyador** [cedricdelpoux/gatsby-source-google-docs#57]
I'd like to separate paragraphs and line breaks (poetry, for example).
Is it possible?

**Comment by linoxyn** [comment]
Because one queries and then inserts the returned HTML content 'as is' from the paragraph format interpreted by the markdown plugin one could access the styling of the paragraphs by using CSS selectors within an HTML container like a <div> or even trick it into a styling where your 'poetry' is written using, for example, `Heading 3` in the Docs and then select those heading elements with your CSS.

**Comment by cedricdelpoux** [comment]
Yes @ilyador  you should try to write some specific css rules for your needs for `p` and `br` tags
